/*----------------------------------------------------------------------------*/
/* Copyright (c) 2018 FIRST. All Rights Reserved.                             */
/* Open Source Software - may be modified and shared by FRC teams. The code   */
/* must be accompanied by the FIRST BSD license file in the root directory of */
/* the project.                                                               */
/*----------------------------------------------------------------------------*/

package frc.robot;
public class constants {
    //k are the drive constants
    public static final double KP = 0;
    public static final double KI = 0;
    public static final double KD = 0;
    public static final double KTolerance = 2;
    //A are arm constants
    public static final double AP = 0;
    public static final double AI = 0;
    public static final double AD = 0;
    public static final double ATolerance = 2;
}
